version: '3'

services:
  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-16-may-2021/luna-group-project/aries/luna:master
    # command: "tail -f /dev/null"
    # command: "python manage.py runserver 0:8000"
    env_file:
      - ./env/prod.env
    command: "sh /scripts/run.sh"
    volumes:
      - static-files:/static-files
      - media-files:/media-files
      - frontend:/frontend/build
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    env_file:
      - ./env/prod.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data


  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static-files:/static-files
      - /etc/letsencrypt:/etc/letsencrypt
      - frontend:/frontend

volumes:
  postgres_volume:
  static-files:
  media-files:
  frontend:
