version: '3'

services:
  backend:
    image: luna_local_dev
    ports:
      - 8000:8000
    env_file:
      - ./env/dev.env
    volumes:
      - ./Backend:/backend
    #command: "tail -f /dev/null"
    command: "sh /scripts/dev.sh"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./env/dev.env
    volumes:
    - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
